package models;
// Generated 6/11/2020 01:22:37 AM by Hibernate Tools 4.3.1



/**
 * Destiny generated by hbm2java
 */
public class Destiny  implements java.io.Serializable {


     private Integer id;
     private User user;
     private String observation;
     private Integer externalId;

    public Destiny() {
    }

	
    public Destiny(User user, String observation) {
        this.user = user;
        this.observation = observation;
    }
    public Destiny(User user, String observation, Integer externalId) {
       this.user = user;
       this.observation = observation;
       this.externalId = externalId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getObservation() {
        return this.observation;
    }
    
    public void setObservation(String observation) {
        this.observation = observation;
    }
    public Integer getExternalId() {
        return this.externalId;
    }
    
    public void setExternalId(Integer externalId) {
        this.externalId = externalId;
    }




}


