package models;
// Generated 6/11/2020 01:22:37 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * RoutePath generated by hbm2java
 */
public class RoutePath  implements java.io.Serializable {


     private Long id;
     private Long destinyId;
     private Long externalId;
     private int userId;
     private BigDecimal longitude;
     private BigDecimal latitude;
     private String speed;
     private String temperature;
     private String humidity;
     private String type;
     private String timeStamp;

    public RoutePath() {
    }

	
    public RoutePath(Long destinyId, int userId) {
        this.destinyId = destinyId;
        this.userId = userId;
    }
    public RoutePath(Long destinyId, Long externalId, int userId, BigDecimal longitude, BigDecimal latitude, String speed, String temperature, String humidity) {
       this.destinyId = destinyId;
       this.externalId = externalId;
       this.userId = userId;
       this.longitude = longitude;
       this.latitude = latitude;
       this.speed = speed;
       this.temperature = temperature;
       this.humidity = humidity;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getDestinyId() {
        return destinyId;
    }

    public void setDestinyId(Long destinyId) {
        this.destinyId = destinyId;
    }

    public Long getExternalId() {
        return externalId;
    }

    public void setExternalId(Long externalId) {
        this.externalId = externalId;
    }
    
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public BigDecimal getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }
    public BigDecimal getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }
    public String getSpeed() {
        return this.speed;
    }
    
    public void setSpeed(String speed) {
        this.speed = speed;
    }
    public String getTemperature() {
        return this.temperature;
    }
    
    public void setTemperature(String temperature) {
        this.temperature = temperature;
    }
    public String getHumidity() {
        return this.humidity;
    }
    
    public void setHumidity(String humidity) {
        this.humidity = humidity;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(String timeStamp) {
        this.timeStamp = timeStamp;
    }

}
