package models;
// Generated 6/11/2020 01:22:37 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String email;
     private String password;
     private String name;
     private String lastName;
     private Set destinies = new HashSet(0);

    public User() {
    }

	
    public User(String email, String password) {
        this.email = email;
        this.password = password;
    }
    public User(String email, String password, String name, String lastName, Set destinies) {
       this.email = email;
       this.password = password;
       this.name = name;
       this.lastName = lastName;
       this.destinies = destinies;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Set getDestinies() {
        return this.destinies;
    }
    
    public void setDestinies(Set destinies) {
        this.destinies = destinies;
    }
}
